import { useState } from 'react';
import { DashboardSection } from '../../../components/CommonBlocks';
import { notify } from '../../../utils/notifications';
import { getInterviewContext } from '../../../api/interviewAgent';

export default function AiAgentTab() {
  const [interviewId, setInterviewId] = useState('');
  const [context, setContext] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleFetch = async (e) => {
    e.preventDefault();
    if (!interviewId.trim()) return;
    setLoading(true);
    setContext(null);
    try {
      const data = await getInterviewContext(interviewId.trim());
      setContext(data);
    } catch (err) {
      notify(err.message ?? 'Failed to fetch AI context.', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <DashboardSection title="AI Interview Context Debugger">
        <p className="muted" style={{ marginBottom: 16 }}>
          Look up the full MongoDB AI context for any scheduled interview. Use this to inspect
          the candidate brief, transcript, and final decision generated by the interview agent.
        </p>
        <form className="settings-form" onSubmit={handleFetch} noValidate>
          <div className="form-row" style={{ alignItems: 'flex-end' }}>
            <div className="form-group" style={{ flex: 1 }}>
              <label>Interview ID</label>
              <input
                type="number"
                min="1"
                value={interviewId}
                onChange={(e) => setInterviewId(e.target.value)}
                placeholder="e.g., 1"
              />
            </div>
            <button className="btn-dark" type="submit" disabled={loading || !interviewId.trim()}>
              {loading ? 'Loading...' : 'Fetch Context'}
            </button>
          </div>
        </form>
      </DashboardSection>

      {context && <ContextViewer context={context} />}
    </div>
  );
}

function ContextViewer({ context }) {
  return (
    <div className="agent-context-viewer">
      <ContextMeta context={context} />
      {context.candidateBrief && <ContextBlock title="Candidate Brief" content={context.candidateBrief} prose />}
      {context.cvSummary && <ContextBlock title="CV Summary" content={context.cvSummary} prose />}
      {context.candidateProfile && <ContextBlock title="Candidate Profile Snapshot" content={context.candidateProfile} />}
      {context.jobContext && <ContextBlock title="Job Context Snapshot" content={context.jobContext} />}
      {context.transcript?.length > 0 && <TranscriptBlock transcript={context.transcript} />}
      {context.decision && <DecisionBlock decision={context.decision} />}
    </div>
  );
}

function ContextMeta({ context }) {
  const rows = [
    ['Interview ID', context.interviewId],
    ['Application ID', context.applicationId],
    ['Candidate ID', context.candidateId],
    ['Job ID', context.jobId],
    ['Status', context.status],
    ['Created', context.createdAt ? new Date(context.createdAt).toLocaleString() : '—'],
    ['Updated', context.updatedAt ? new Date(context.updatedAt).toLocaleString() : '—'],
  ];

  return (
    <DashboardSection title="Overview">
      <table className="agent-meta-table">
        <tbody>
          {rows.map(([label, value]) => (
            <tr key={label}>
              <th>{label}</th>
              <td>
                {value != null ? (
                  <span className={label === 'Status' ? `agent-status ${String(value).toLowerCase()}` : ''}>
                    {String(value)}
                  </span>
                ) : <span className="muted">—</span>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </DashboardSection>
  );
}

function ContextBlock({ title, content, prose = false }) {
  const [expanded, setExpanded] = useState(true);

  const renderContent = () => {
    if (prose && typeof content === 'string') {
      return <p className="agent-prose">{content}</p>;
    }
    if (typeof content === 'string') {
      return <pre className="agent-raw">{content}</pre>;
    }
    return <pre className="agent-raw">{JSON.stringify(content, null, 2)}</pre>;
  };

  return (
    <DashboardSection
      title={
        <button className="agent-section-toggle" onClick={() => setExpanded((p) => !p)} type="button">
          {title} <span>{expanded ? '▲' : '▼'}</span>
        </button>
      }
    >
      {expanded && renderContent()}
    </DashboardSection>
  );
}

function TranscriptBlock({ transcript }) {
  const [expanded, setExpanded] = useState(true);

  return (
    <DashboardSection
      title={
        <button className="agent-section-toggle" onClick={() => setExpanded((p) => !p)} type="button">
          Transcript ({transcript.length} turns) <span>{expanded ? '▲' : '▼'}</span>
        </button>
      }
    >
      {expanded && (
        <div className="agent-transcript">
          {transcript.map((entry, idx) => {
            const role = entry.role ?? (idx % 2 === 0 ? 'AI' : 'CANDIDATE');
            return (
              <div key={idx} className={`agent-turn ${String(role).toLowerCase()}`}>
                <span className="agent-turn-role">{role}</span>
                <p>{entry.content ?? entry.message ?? JSON.stringify(entry)}</p>
              </div>
            );
          })}
        </div>
      )}
    </DashboardSection>
  );
}

function DecisionBlock({ decision }) {
  const score = decision.score ?? decision.overallScore;
  const recommendation = decision.recommendation;
  const feedback = decision.feedback;
  const decidedAt = decision.decidedAt ? new Date(decision.decidedAt).toLocaleString() : null;

  const recClass = recommendation
    ? { HIRE: 'hire', CONSIDER: 'consider', REJECT: 'reject' }[recommendation] ?? ''
    : '';

  return (
    <DashboardSection title="Final Decision">
      <div className="agent-decision">
        {score != null && (
          <div className="agent-score">
            <span className="agent-score-number">{score}</span>
            <span className="muted">/ 100</span>
          </div>
        )}
        {recommendation && (
          <span className={`agent-recommendation ${recClass}`}>{recommendation}</span>
        )}
        {feedback && <p className="agent-feedback">{feedback}</p>}
        {decidedAt && <p className="muted small">Decided at: {decidedAt}</p>}
      </div>
    </DashboardSection>
  );
}
